#!/bin/bash

echo "Script name: $0"
echo "First argument: $1"
echo "Second argument: $2"
echo "Number of arguments: $#"
echo "All arguments using \$@: $@"
echo "All arguments using \$*: $*"

echo "Using \$@:"
for arg in "$@"; do
    echo "$arg"
done

echo "Using \$*:"
for arg in $*; do
    echo "$arg"
done

