#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:
# Accepts 4 parameters : 
# 	1- The path to the file to be transferred
# 	2- The IP of the server we want to transfer the file to
# 	3- The username scp connects with
#	4- The path to the SSH private key that scp uses
# NOTE IMPORTANT: if less than 3 parameters passed, this script will diplay:
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# 
# scp will transfer the file to the user home directory ~/
# Strict host key checking should be disabled when using scp.

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"
DEST="/home/ubuntu"

if [[ $# -le 3 ]];
then
	ECHO 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	scp -o 'StrictHostKeyChecking=no' -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":"$DEST"
fi
