#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# Requirements:
# 	- The redirection must be a “301 Moved Permanently”
# 	- You answer file should be a Bash script containing commands to
#    automatically configure a Ubuntu machine to respect above requirements
# 	- write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task


# using what i have done in task one
sudo apt-get -y update
sudo apt-get -y install nginx

sudo touch /var/www/html/index.html

sudo chmod 777 /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html

# setting nginx configurtion server 
new_str="server_name _;\n\n\tlocation = \/redirect_me\/ {\n\t\treturn 301 https:\/\/github.com\/Drihmia;\n\t}"
if ! sudo grep -q "location = \/redirectme\/ "; then
	sudo sed -i 's/server_name _;/'"$new_str"'/' /etc/nginx/sites-available/default
fi

sudo nginx -s reload
