#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# Requirements:
# 	- The redirection must be a “301 Moved Permanently”
# 	- You answer file should be a Bash script containing commands to
#    automatically configure a Ubuntu machine to respect above requirements
# 	- write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get update -y
sudo apt-get install nginx -y

new_str_err="server_name _;\n\terror_page 404 \/404.html;"

new_str_loc="server_name _;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t\t}"

# Setting a 404 error file.
sudo touch /var/www/html/404.html
sudo chmod 777 /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo chmod 644 /var/www/html/404.html

# check if the config's file already exist otherwise I exit.
if [ ! -f "/etc/nginx/sites-available/default" ]; then
    echo "Nginx configuration file not found. Please adjust the path."
    exit 1
fi

# check if the string "location = 404.html" in the file before add it
if ! grep -q "location = \/404.html " /etc/nginx/sites-available/default; then
	sudo sed -i 's/server_name _;/'"$new_str_loc"'/' /etc/nginx/sites-available/default
fi

# check if the string "error_error" in the file before add it
if ! sudo grep -q  "error_page 404 \/404.html;" /etc/nginx/sites-available/default; then
	sudo sed -i 's/server_name _;/'"$new_str_err"'/' /etc/nginx/sites-available/default
fi

# restart the nginx.
sudo service nginx restart
