#!/usr/bin/env bash
# a Bash script that:
 	# Creates the file /var/run/myscript.pid containing its PID.
	# Displays To infinity and beyond indefinitely
	# Displays I hate the kill command when receiving a SIGTERM signal
	# Displays Y U no love me?! when receiving a SIGINT signal
	# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

# a funtion that handles the seg term, and print to stdout a message and rm the file that has been created
# then it exit
segterm_handler()
{
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit
}

# a funtion that handles the seg quit, rm the file that has been created
# then it exit
segquit_handler()
{
	rm -f /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid
trap 'segterm_handler' TERM
trap 'segquit_handler' QUIT
trap 'echo "Y U no love me?!"' SIGINT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
