#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process.
# I must use kill

pids=$(pgrep -lf 'bash ./4-to_infinity_and_beyond' | awk '{print $1}')
if [ -n "$pids" ]
then
	kill "$pids"
fi
