#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user
#You must use the while loop (for and until are forbidden)

file=/etc/passwd

if [[ -e $file ]]
then
	while IFS= read -r line
	do
		if [[ $line == *":"* ]]
		then
			echo "$line" | cut -d ":" -f1,3,6
		fi
	done < $file
fi

