#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user
#You must use the while loop (for and until are forbidden)

file=/etc/passwd
i=1

if [[ -e $file ]]
then
	while IFS= read -r line
	do
		if [[ $line == *":"* ]]
		then
			USERNAME="$(echo "$line" | cut -d ":" -f1)"
			PASSWORD="$(echo "$line" | cut -d ":" -f2)"
			USER_ID="$(echo "$line" | cut -d ":" -f3)"
			GROUP_ID="$(echo "$line" | cut -d ":" -f4)"
			INFO="$(echo "$line" | cut -d ":" -f5)"
			HOME_DIRECTORY="$(echo "$line" | cut -d ":" -f6)"
			COMMAND_SHELL="$(echo "$line" | cut -d ":" -f7)"

			echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID´'´s place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID $INFO"
		fi
	
		((i++))
	done < $file
fi
