#!/usr/bin/env bash
# a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
#You must use the while loop (for and until are forbidden)
#You must use the if statement
# shellcheck disable=2034

word="Best School"
i=0
while [[ $i -lt 10 ]]
do
	echo "$word"
	if [[ $i -eq 8 ]]
	then
		echo "Hi"
	fi
	((i++))
done
