#!/usr/bin/env bash
#a Bash script that displays Best School 10 times using while loop.
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
#You must use the while loop (for and until are forbidden)
#You must use the if, elif and else statements
# shellcheck disable=2034

word="Best School"
i=1
while [[ $i -le 10 ]]
do
	if [[ $i -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $i -eq 8 ]]
	then
		echo "good luck"
	else
		echo "$word"
	fi
	((i++))
done
