#!/usr/bin/env bash
#a Bash script that displays: The content of the current directory in a list format
#Where only the part of the name after the first dash is displayed (refer to the example)
#You must use the for loop (while and until are forbidden)
#Do not display hidden files
# shellcheck disable=2034

list=$(ls)
for file in $list
do
	echo "$file" | cut -d "-" -f2
done

