#!/usr/bin/env bash
# a Bash script that configures the container to fit the below requirements
chmod +r /etc/nginx/nginx.conf
bash -c "echo \"user nginx;\" >> \"/etc/nginx/nginx.conf\""
bash -c "kill -9 $(pgrep apache2)"
bash -c "sudo -u nginx service nginx restart"
chmod a-r /etc/nginx/nginx.conf
