#!/usr/bin/env bash
# a Bash script that configures the container to fit the below requirements
chmod +r /etc/nginx/nginx.conf
echo "user nginx; >> /etc/nginx/nginx.conf"
sed -i 's/80/8080/g' '/etc/nginx/sites-available/default'
kill -9 $(pgrep apache2)
sudo -u nginx service nginx restart
