#!/usr/bin/env bash
# a Bash script that configures 
chmod +r /etc/nginx/nginx.conf
sed -i '/^#user/c\user nginx;' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
